project-repo-url: https://github.com/ScottLogic/d3-financial-components

component-ids: [series, indicators, math, scale, utilities]

components:
  series:
    name: Series
  indicators:
    name: Indicators
  math:
    name: Math
  scale:
    name: Scale
  utilities:
    name: Utilities
