project-repo-url: https://github.com/ScottLogic/d3fc

component-ids: [annotation, chart, series, indicator, scale, layout, datagenerator]

components:
  annotation:
    name: Annotations
  chart:
    name: Chart
  series:
    name: Series
  indicator:
    name: Indicators
  scale:
    name: Scale
  layout:
    name: Layout
  datagenerator:
    name: Data Generator
