project-repo-url: https://github.com/ScottLogic/d3-financial-components

component-ids: [chart, series, indicators, scale, layout, datagenerator]

components:
  chart:
    name: Chart
  series:
    name: Series
  indicators:
    name: Indicators
  scale:
    name: Scale
  layout:
    name: Layout
  datagenerator:
    name: Data Generator
